/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DangNhap_Controller;
import view.QuanLyCuaHangTapHoa_View;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class DangNhap_View extends javax.swing.JFrame {

    /**
     * Creates new form LoginV1
     */
    public DangNhap_View() {
        initComponents();
        this.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        DangNhapHeThong_lbl = new javax.swing.JLabel();
        MatKhau_lbl = new javax.swing.JLabel();
        DangNhap_btn = new javax.swing.JButton();
        LamMoi_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        TaiKhoan_lbl = new javax.swing.JLabel();
        TaiKhoan_tf = new javax.swing.JTextField();
        MatKhau_pf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        jSeparator2.setForeground(new java.awt.Color(255, 153, 51));

        DangNhapHeThong_lbl.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DangNhapHeThong_lbl.setText("Đăng nhập vào hệ thống");

        MatKhau_lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        MatKhau_lbl.setText("Mật khẩu :");

        DangNhap_btn.setBackground(new java.awt.Color(198, 217, 234));
        DangNhap_btn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DangNhap_btn.setLabel("Đăng nhập");
        DangNhap_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangNhap_btnActionPerformed(evt);
            }
        });

        LamMoi_btn.setBackground(new java.awt.Color(198, 217, 234));
        LamMoi_btn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LamMoi_btn.setText("Làm mới");
        LamMoi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoi_btnActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 153, 51));

        TaiKhoan_lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TaiKhoan_lbl.setText("Tài khoản:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(DangNhapHeThong_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(TaiKhoan_lbl)
                        .addGap(37, 37, 37)
                        .addComponent(TaiKhoan_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(MatKhau_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(MatKhau_pf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(DangNhap_btn)
                        .addGap(33, 33, 33)
                        .addComponent(LamMoi_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(DangNhapHeThong_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaiKhoan_lbl)
                    .addComponent(TaiKhoan_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MatKhau_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(MatKhau_pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DangNhap_btn)
                    .addComponent(LamMoi_btn))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DangNhap_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangNhap_btnActionPerformed
        // TODO add your handling code here:
        DangNhap_Controller dn = new DangNhap_Controller();
        boolean kiemtra = dn.DangNhap(TaiKhoan_tf.getText(),MatKhau_pf.getText());
        if(kiemtra == true){
            JOptionPane.showMessageDialog(this,"Dang nhap thanh cong");
            QuanLyCuaHangTapHoa_View qlchth = new QuanLyCuaHangTapHoa_View();
            this.setVisible(false);
        } else{
            JOptionPane.showMessageDialog(this,"Dang nhap that bai","Loi",JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_DangNhap_btnActionPerformed

    private void LamMoi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoi_btnActionPerformed
        // TODO add your handling code here:
        TaiKhoan_tf.setText("");
        MatKhau_pf.setText("");
        
    }//GEN-LAST:event_LamMoi_btnActionPerformed

    /**
     * @param args the command line arguments
     */
   
      
        

        
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DangNhapHeThong_lbl;
    private javax.swing.JButton DangNhap_btn;
    private javax.swing.JButton LamMoi_btn;
    private javax.swing.JLabel MatKhau_lbl;
    private javax.swing.JTextField MatKhau_pf;
    private javax.swing.JLabel TaiKhoan_lbl;
    private javax.swing.JTextField TaiKhoan_tf;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
