/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;
import net.miginfocom.swing.MigLayout;
import view.HoaDonMuaHang_View;
import view.QuanLyMatHang_View;
import view.TaoMauGradient_View;
import view.TimKiemSanPham_View;

/**
 *
 * @author admin
 */
public class QuanLyCuaHangTapHoaAdmin_View extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyCuaHangTapHoa_View
     */
    public QuanLyCuaHangTapHoaAdmin_View() {
        initComponents();
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new TaoMauGradient_View(246,207,190,185,220,242);
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ThongKeSanPham_pn = new javax.swing.JPanel();
        Icon_lbl2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ThongKeDoanhThu_pn = new javax.swing.JPanel();
        Icon_lbl4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DangXuat_pn = new javax.swing.JPanel();
        Icon_lbl6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar5.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar5.add(jMenu12);

        jMenuItem3.setText("jMenuItem3");

        jMenu13.setText("File");
        jMenuBar6.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar6.add(jMenu14);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí cửa hàng tạp hóa");
        setMinimumSize(new java.awt.Dimension(911, 406));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new MigLayout("wrap 2, inset 30", "[fill, 100]10[fill, 100]", "[]10[]"));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/Logo_Image.png"))); // NOI18N
        jLabel1.setText("Application");

        ThongKeSanPham_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongKeSanPham_pn.setOpaque(false);
        ThongKeSanPham_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeSanPham_pnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ThongKeSanPham_pnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ThongKeSanPham_pnMouseExited(evt);
            }
        });

        Icon_lbl2.setForeground(new java.awt.Color(51, 0, 51));
        Icon_lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/ThongKeSanPham_Icon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel5.setText("Thống kê sản phẩm");

        javax.swing.GroupLayout ThongKeSanPham_pnLayout = new javax.swing.GroupLayout(ThongKeSanPham_pn);
        ThongKeSanPham_pn.setLayout(ThongKeSanPham_pnLayout);
        ThongKeSanPham_pnLayout.setHorizontalGroup(
            ThongKeSanPham_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongKeSanPham_pnLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Icon_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongKeSanPham_pnLayout.setVerticalGroup(
            ThongKeSanPham_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeSanPham_pnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThongKeSanPham_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Icon_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ThongKeSanPham_pnLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Icon_lbl2, jLabel5});

        ThongKeDoanhThu_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongKeDoanhThu_pn.setOpaque(false);
        ThongKeDoanhThu_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeDoanhThu_pnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ThongKeDoanhThu_pnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ThongKeDoanhThu_pnMouseExited(evt);
            }
        });

        Icon_lbl4.setForeground(new java.awt.Color(51, 0, 51));
        Icon_lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/ThongKeDoanhThu_Icon.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel7.setText("Thống kê doanh thu");

        javax.swing.GroupLayout ThongKeDoanhThu_pnLayout = new javax.swing.GroupLayout(ThongKeDoanhThu_pn);
        ThongKeDoanhThu_pn.setLayout(ThongKeDoanhThu_pnLayout);
        ThongKeDoanhThu_pnLayout.setHorizontalGroup(
            ThongKeDoanhThu_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongKeDoanhThu_pnLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Icon_lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongKeDoanhThu_pnLayout.setVerticalGroup(
            ThongKeDoanhThu_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeDoanhThu_pnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThongKeDoanhThu_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Icon_lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DangXuat_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DangXuat_pn.setOpaque(false);
        DangXuat_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuat_pnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DangXuat_pnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DangXuat_pnMouseExited(evt);
            }
        });

        Icon_lbl6.setForeground(new java.awt.Color(51, 0, 51));
        Icon_lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/DangXuat_Icon.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setText("Đăng Xuất");

        javax.swing.GroupLayout DangXuat_pnLayout = new javax.swing.GroupLayout(DangXuat_pn);
        DangXuat_pn.setLayout(DangXuat_pnLayout);
        DangXuat_pnLayout.setHorizontalGroup(
            DangXuat_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuat_pnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Icon_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DangXuat_pnLayout.setVerticalGroup(
            DangXuat_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuat_pnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DangXuat_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Icon_lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
            .addComponent(ThongKeSanPham_pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ThongKeDoanhThu_pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DangXuat_pn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThongKeDoanhThu_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThongKeSanPham_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DangXuat_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/Main_Image.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ThongKeDoanhThu_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeDoanhThu_pnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        ThongKeDoanhThu_View tkdt = new ThongKeDoanhThu_View();
    }//GEN-LAST:event_ThongKeDoanhThu_pnMouseClicked

    private void ThongKeSanPham_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeSanPham_pnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        ThongKeSanPham_View thongkesp = new ThongKeSanPham_View();
    }//GEN-LAST:event_ThongKeSanPham_pnMouseClicked

    private void ThongKeDoanhThu_pnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeDoanhThu_pnMouseEntered
        // TODO add your handling code here:
        hover(ThongKeDoanhThu_pn);
    }//GEN-LAST:event_ThongKeDoanhThu_pnMouseEntered

    private void ThongKeDoanhThu_pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeDoanhThu_pnMouseExited
        // TODO add your handling code here:
        un_hover(ThongKeDoanhThu_pn);
    }//GEN-LAST:event_ThongKeDoanhThu_pnMouseExited

    private void ThongKeSanPham_pnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeSanPham_pnMouseEntered
        // TODO add your handling code here:
        hover(ThongKeSanPham_pn);
    }//GEN-LAST:event_ThongKeSanPham_pnMouseEntered

    private void ThongKeSanPham_pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeSanPham_pnMouseExited
        // TODO add your handling code here:
        un_hover(ThongKeSanPham_pn);
    }//GEN-LAST:event_ThongKeSanPham_pnMouseExited

    private void DangXuat_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuat_pnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        DangNhap_View dnv = new DangNhap_View();

    }//GEN-LAST:event_DangXuat_pnMouseClicked

    private void DangXuat_pnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuat_pnMouseEntered
        // TODO add your handling code here:
        hover(DangXuat_pn);

    }//GEN-LAST:event_DangXuat_pnMouseEntered

    private void DangXuat_pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuat_pnMouseExited
        // TODO add your handling code here:
        un_hover(DangXuat_pn);
    }//GEN-LAST:event_DangXuat_pnMouseExited

    private void hover(JPanel panel) {
        Border RaisedBevelBorder = BorderFactory.createRaisedBevelBorder();
        panel.setBorder(RaisedBevelBorder);
    }

    private void un_hover(JPanel panel) {
        Border EmptyBorder = BorderFactory.createEmptyBorder();
        panel.setBorder(EmptyBorder);
    }

    public static void main(String[] args) {
        QuanLyCuaHangTapHoaAdmin_View qlchth = new QuanLyCuaHangTapHoaAdmin_View();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DangXuat_pn;
    private javax.swing.JLabel Icon_lbl2;
    private javax.swing.JLabel Icon_lbl4;
    private javax.swing.JLabel Icon_lbl6;
    private javax.swing.JPanel ThongKeDoanhThu_pn;
    private javax.swing.JPanel ThongKeSanPham_pn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
