/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author admin
 */
public class QuanLyCuaHangTapHoa_View extends javax.swing.JFrame {
    
    
    /**
     * Creates new form QuanLyCuaHangTapHoa_View
     */
    public QuanLyCuaHangTapHoa_View() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        QuanLiGiaoDich_mn = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        TimKiemMatHang_mni = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí cửa hàng tạp hóa");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(337, 30));

        QuanLiGiaoDich_mn.setText("Quản lí giao dịch");
        QuanLiGiaoDich_mn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        QuanLiGiaoDich_mn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLiGiaoDich_mnMouseClicked(evt);
            }
        });
        jMenuBar1.add(QuanLiGiaoDich_mn);

        jMenu3.setText("Quản lí mặt hàng");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        TimKiemMatHang_mni.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TimKiemMatHang_mni.setText("Tìm kiếm mặt hàng");
        TimKiemMatHang_mni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TimKiemMatHang_mniMousePressed(evt);
            }
        });
        jMenu3.add(TimKiemMatHang_mni);

        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu1);

        jMenu5.setText("Quản lí nhập hàng");
        jMenu5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu4.setText("Báo cáo và thống kê");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItem1.setText("Thống kê sản phẩm");
        jMenu4.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItem2.setText("Thống kê doanh thu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void QuanLiGiaoDich_mnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiGiaoDich_mnMouseClicked
        // TODO add your handling code here:
        HoaDonMuaHang_View hdmh = new HoaDonMuaHang_View();
        this.setVisible(false);
        
    }//GEN-LAST:event_QuanLiGiaoDich_mnMouseClicked

    private void TimKiemMatHang_mniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimKiemMatHang_mniMousePressed
        // TODO add your handling code here:
         TimKiemSanPham_View tksp = new TimKiemSanPham_View();
        this.setVisible(false);
    }//GEN-LAST:event_TimKiemMatHang_mniMousePressed

    
   
 
            
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu QuanLiGiaoDich_mn;
    private javax.swing.JMenuItem TimKiemMatHang_mni;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    // End of variables declaration//GEN-END:variables
}
