/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.QuanLyCuaHangTapHoaEmployee_View;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;
import net.miginfocom.swing.MigLayout;
import view.HoaDonMuaHang_View;
import view.QuanLyMatHang_View;
import view.TaoMauGradient_View;
import view.TimKiemSanPham_View;

/**
 *
 * @author admin
 */
public class QuanLyCuaHangTapHoaEmployee_View extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyCuaHangTapHoa_View
     */
    public QuanLyCuaHangTapHoaEmployee_View() {
        initComponents();
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new TaoMauGradient_View(246,207,190,185,220,242);
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        QuanLyNhapSanPham_pn = new javax.swing.JPanel();
        Icon_lbl5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        QuanLiGiaoDich_pn = new javax.swing.JPanel();
        Icon_lbl3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        QuanLiMatHang_pn = new javax.swing.JPanel();
        Icon_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        QuanLiKhachHang_pn = new javax.swing.JPanel();
        Icon_lbl7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DangXuat_pn = new javax.swing.JPanel();
        Icon_lbl6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar5.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar5.add(jMenu12);

        jMenuItem3.setText("jMenuItem3");

        jMenu13.setText("File");
        jMenuBar6.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar6.add(jMenu14);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí cửa hàng tạp hóa");
        setMinimumSize(new java.awt.Dimension(911, 406));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new MigLayout("wrap 2, inset 30", "[fill, 100]10[fill, 100]", "[]10[]"));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/Logo_Image.png"))); // NOI18N
        jLabel1.setText("Application");

        QuanLyNhapSanPham_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyNhapSanPham_pn.setOpaque(false);
        QuanLyNhapSanPham_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLyNhapSanPham_pnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuanLyNhapSanPham_pnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuanLyNhapSanPham_pnMouseExited(evt);
            }
        });

        Icon_lbl5.setForeground(new java.awt.Color(51, 0, 51));
        Icon_lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/QuanLiNhapHang_Icon.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel8.setText("Quản lý nhập sản phẩm");

        javax.swing.GroupLayout QuanLyNhapSanPham_pnLayout = new javax.swing.GroupLayout(QuanLyNhapSanPham_pn);
        QuanLyNhapSanPham_pn.setLayout(QuanLyNhapSanPham_pnLayout);
        QuanLyNhapSanPham_pnLayout.setHorizontalGroup(
            QuanLyNhapSanPham_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyNhapSanPham_pnLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Icon_lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyNhapSanPham_pnLayout.setVerticalGroup(
            QuanLyNhapSanPham_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyNhapSanPham_pnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(14, 14, 14))
            .addComponent(Icon_lbl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        QuanLiGiaoDich_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLiGiaoDich_pn.setOpaque(false);
        QuanLiGiaoDich_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLiGiaoDich_pnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuanLiGiaoDich_pnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuanLiGiaoDich_pnMouseExited(evt);
            }
        });

        Icon_lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/QuanLiGiaoDich_Icon.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setText("Quản lí giao dịch");

        javax.swing.GroupLayout QuanLiGiaoDich_pnLayout = new javax.swing.GroupLayout(QuanLiGiaoDich_pn);
        QuanLiGiaoDich_pn.setLayout(QuanLiGiaoDich_pnLayout);
        QuanLiGiaoDich_pnLayout.setHorizontalGroup(
            QuanLiGiaoDich_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLiGiaoDich_pnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Icon_lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLiGiaoDich_pnLayout.setVerticalGroup(
            QuanLiGiaoDich_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLiGiaoDich_pnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLiGiaoDich_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Icon_lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuanLiMatHang_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLiMatHang_pn.setOpaque(false);
        QuanLiMatHang_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLiMatHang_pnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuanLiMatHang_pnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuanLiMatHang_pnMouseExited(evt);
            }
        });

        Icon_lbl.setForeground(new java.awt.Color(51, 0, 51));
        Icon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/QuanLiMatHang_Icon.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setText("Quản lí mặt hàng");

        javax.swing.GroupLayout QuanLiMatHang_pnLayout = new javax.swing.GroupLayout(QuanLiMatHang_pn);
        QuanLiMatHang_pn.setLayout(QuanLiMatHang_pnLayout);
        QuanLiMatHang_pnLayout.setHorizontalGroup(
            QuanLiMatHang_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLiMatHang_pnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Icon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLiMatHang_pnLayout.setVerticalGroup(
            QuanLiMatHang_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLiMatHang_pnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLiMatHang_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Icon_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuanLiKhachHang_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLiKhachHang_pn.setOpaque(false);
        QuanLiKhachHang_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLiKhachHang_pnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuanLiKhachHang_pnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuanLiKhachHang_pnMouseExited(evt);
            }
        });

        Icon_lbl7.setForeground(new java.awt.Color(51, 0, 51));
        Icon_lbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/QuanLiKhachHang_Icon.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel10.setText("Quản lí khách hàng");

        javax.swing.GroupLayout QuanLiKhachHang_pnLayout = new javax.swing.GroupLayout(QuanLiKhachHang_pn);
        QuanLiKhachHang_pn.setLayout(QuanLiKhachHang_pnLayout);
        QuanLiKhachHang_pnLayout.setHorizontalGroup(
            QuanLiKhachHang_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLiKhachHang_pnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Icon_lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLiKhachHang_pnLayout.setVerticalGroup(
            QuanLiKhachHang_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLiKhachHang_pnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLiKhachHang_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Icon_lbl7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DangXuat_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DangXuat_pn.setOpaque(false);
        DangXuat_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuat_pnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DangXuat_pnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DangXuat_pnMouseExited(evt);
            }
        });

        Icon_lbl6.setForeground(new java.awt.Color(51, 0, 51));
        Icon_lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/DangXuat_Icon.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setText("Đăng Xuất");

        javax.swing.GroupLayout DangXuat_pnLayout = new javax.swing.GroupLayout(DangXuat_pn);
        DangXuat_pn.setLayout(DangXuat_pnLayout);
        DangXuat_pnLayout.setHorizontalGroup(
            DangXuat_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuat_pnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Icon_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DangXuat_pnLayout.setVerticalGroup(
            DangXuat_pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuat_pnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Icon_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
            .addComponent(QuanLiGiaoDich_pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyNhapSanPham_pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLiKhachHang_pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DangXuat_pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLiMatHang_pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyNhapSanPham_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLiGiaoDich_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLiMatHang_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLiKhachHang_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DangXuat_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/Main_Image.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void QuanLyNhapSanPham_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyNhapSanPham_pnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        QuanLyNhapSanPham_View qlnsp = new QuanLyNhapSanPham_View();
        //ThongKeSanPham_View thongkesp = new ThongKeSanPham_View(); khoi tao doi tuong view cua quan li nhap hang
    }//GEN-LAST:event_QuanLyNhapSanPham_pnMouseClicked

    private void QuanLyNhapSanPham_pnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyNhapSanPham_pnMouseEntered
        // TODO add your handling code here:
        hover(QuanLyNhapSanPham_pn);
    }//GEN-LAST:event_QuanLyNhapSanPham_pnMouseEntered

    private void QuanLyNhapSanPham_pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyNhapSanPham_pnMouseExited
        // TODO add your handling code here:
        un_hover(QuanLyNhapSanPham_pn);
    }//GEN-LAST:event_QuanLyNhapSanPham_pnMouseExited

    private void QuanLiGiaoDich_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiGiaoDich_pnMouseClicked
        this.setVisible(false);
        HoaDonMuaHang_View hdmh = new HoaDonMuaHang_View();
    }//GEN-LAST:event_QuanLiGiaoDich_pnMouseClicked

    private void QuanLiGiaoDich_pnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiGiaoDich_pnMouseEntered
        // TODO add your handling code here:
        hover(QuanLiGiaoDich_pn);
    }//GEN-LAST:event_QuanLiGiaoDich_pnMouseEntered

    private void QuanLiGiaoDich_pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiGiaoDich_pnMouseExited
        // TODO add your handling code here:
        un_hover(QuanLiGiaoDich_pn);
    }//GEN-LAST:event_QuanLiGiaoDich_pnMouseExited

    private void QuanLiMatHang_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiMatHang_pnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            QuanLyMatHang_View qlmh = new QuanLyMatHang_View();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyCuaHangTapHoaEmployee_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_QuanLiMatHang_pnMouseClicked

    private void QuanLiMatHang_pnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiMatHang_pnMouseEntered
        // TODO add your handling code here:
        hover(QuanLiMatHang_pn);
    }//GEN-LAST:event_QuanLiMatHang_pnMouseEntered

    private void QuanLiMatHang_pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiMatHang_pnMouseExited
        // TODO add your handling code here:
        un_hover(QuanLiMatHang_pn);
    }//GEN-LAST:event_QuanLiMatHang_pnMouseExited

    private void QuanLiKhachHang_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiKhachHang_pnMouseClicked
        // TODO add your handling code here:\
        this.setVisible(false);
        QuanLyKhachHang_View qlkh = new QuanLyKhachHang_View();
    }//GEN-LAST:event_QuanLiKhachHang_pnMouseClicked

    private void QuanLiKhachHang_pnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiKhachHang_pnMouseEntered
        // TODO add your handling code here:
        hover(QuanLiKhachHang_pn);
    }//GEN-LAST:event_QuanLiKhachHang_pnMouseEntered

    private void QuanLiKhachHang_pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiKhachHang_pnMouseExited
        // TODO add your handling code here:
        un_hover(QuanLiKhachHang_pn);
    }//GEN-LAST:event_QuanLiKhachHang_pnMouseExited

    private void DangXuat_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuat_pnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        DangNhap_View dnv = new DangNhap_View();
    }//GEN-LAST:event_DangXuat_pnMouseClicked

    private void DangXuat_pnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuat_pnMouseEntered
        // TODO add your handling code here:
        hover(DangXuat_pn);
    }//GEN-LAST:event_DangXuat_pnMouseEntered

    private void DangXuat_pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuat_pnMouseExited
        // TODO add your handling code here:
        un_hover(DangXuat_pn);
    }//GEN-LAST:event_DangXuat_pnMouseExited

    private void hover(JPanel panel) {
        Border RaisedBevelBorder = BorderFactory.createRaisedBevelBorder();
        panel.setBorder(RaisedBevelBorder);
    }

    private void un_hover(JPanel panel) {
        Border EmptyBorder = BorderFactory.createEmptyBorder();
        panel.setBorder(EmptyBorder);
    }

    public static void main(String[] args) {
        QuanLyCuaHangTapHoaEmployee_View qlchth = new QuanLyCuaHangTapHoaEmployee_View();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DangXuat_pn;
    private javax.swing.JLabel Icon_lbl;
    private javax.swing.JLabel Icon_lbl3;
    private javax.swing.JLabel Icon_lbl5;
    private javax.swing.JLabel Icon_lbl6;
    private javax.swing.JLabel Icon_lbl7;
    private javax.swing.JPanel QuanLiGiaoDich_pn;
    private javax.swing.JPanel QuanLiKhachHang_pn;
    private javax.swing.JPanel QuanLiMatHang_pn;
    private javax.swing.JPanel QuanLyNhapSanPham_pn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
